import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Traffic Lights</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.card}>
          <div className={styles.trafficLight}>
            <div className={styles.lightRed}></div>
            <div className={styles.lightYellow}></div>
            <div className={styles.lightGreen}></div>
          </div>
          <div className={styles.label}>
            The light is red.
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
